<a href="https://colab.research.google.com/github/Muyiiwaa/machine_learning_notes/blob/master/Intro_to_deep_learning_with_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# BASIC TENSOR OPERATION IN PYTORCH

In [2]:
import torch

torch.__version__

'2.6.0+cu124'

## Creating Tensors.

Scaler: $ tensor_A = 2$

Vector: $ tensor_B = \begin{bmatrix} 2 \\ 1 \end{bmatrix}$

Matrix: $ tensor_C = \begin{bmatrix} 2 & 1 \\ 4 & 7 \end{bmatrix}$


In [43]:
# creating tensors

tensor_a = torch.tensor(5)
tensor_b = torch.tensor(data= [2,1])
tensor_c = torch.tensor(data= [[2,1],
                               [4, 7]])

print(tensor_a)
print('=' * 30)
print(tensor_b)
print('=' * 30)
print(tensor_c)
print('=' * 30)

tensor(5)
tensor([2, 1])
tensor([[2, 1],
        [4, 7]])


In [19]:
## understanding tensor types and dimenstion

print(f'tensor_a is of dimension: {tensor_a.dim()}')
print(f'tensor_b is of dimension: {tensor_b.dim()}')
print(f'tensor_c is of dimension: {tensor_c.dim()}')

tensor_a is of dimension: 0
tensor_b is of dimension: 1
tensor_c is of dimension: 2


## Performing basic maths operation on tensors

### ADDITION

$ matrix_a = \begin{bmatrix} 1 & 2 \\ 3 & 5 \end{bmatrix} $
$ matrix_b = \begin{bmatrix} 2 & 4 \\ 1 & 6 \end{bmatrix} $

$suMmatrix = \begin{bmatrix} 1 & 2 \\ 3 & 5 \end{bmatrix}$ + $\begin{bmatrix} 2 & 4 \\ 1 & 6 \end{bmatrix}$ = $\begin{bmatrix} 3 & 6 \\ 4 & 11 \end{bmatrix}$

In [ ]:
matrix_a = torch.tensor([[1,2],
            [3, 5]])
matrix_b = torch.tensor([[2, 4],
            [1, 6]])

print(f'matrix_a:\n {matrix_a}')
print(f'matrix_b:\n {matrix_b}')

# sum
sum_matrix = matrix_a + matrix_b
print('*'*25)
print(f'sum_matrix:\n {sum_matrix}')

##Subtraction

$ matrix_a = \begin{bmatrix} 1 & 2 \\ 3 & 5 \end{bmatrix} $
$ matrix_b = \begin{bmatrix} 2 & 4 \\ 1 & 6 \end{bmatrix} $

$diffmatrix = \begin{bmatrix} 1 & 2 \\ 3 & 5 \end{bmatrix} - \begin{bmatrix} 2 & 4 \\ 1 & 6 \end{bmatrix} = \begin{bmatrix} -1 & -2 \\ 2 & -1 \end{bmatrix}$

In [44]:
# difference
diff_matrix = matrix_a - matrix_b
print('*'*25)
print(f'diff_matrix:\n {diff_matrix}')

*************************
diff_matrix:
 tensor([[ 1,  1],
        [-3, -2]])


### ELEMENTWISE PRODUCT
$ matrix_a = \begin{bmatrix} 1 & 2 \\ 3 & 5 \end{bmatrix} $
$ matrix_b = \begin{bmatrix} 2 & 4 \\ 1 & 6 \end{bmatrix} $

$elemproduct = \begin{bmatrix} 1 & 2 \\ 3 & 5 \end{bmatrix} \circ \begin{bmatrix} 2 & 4 \\ 1 & 6 \end{bmatrix} = \begin{bmatrix} 2 & 8 \\ 3 & 30 \end{bmatrix}$

In [45]:
# products
product_matrix = matrix_a * matrix_b
print('*'*25)
print(f'product_matrix:\n {product_matrix}')

*************************
product_matrix:
 tensor([[ 2,  6],
        [-2,  8]])


## MATRIX MULTIPLICATION
$ matrix_a = \begin{bmatrix} 1 & 2 \\ 3 & 5 \end{bmatrix} $
$ matrix_b = \begin{bmatrix} 2 & 4 \\ 1 & 6 \end{bmatrix} $

$matmul = \begin{bmatrix} 1 & 2 \\ 3 & 5 \end{bmatrix} \cdot \begin{bmatrix} 2 & 4 \\ 1 & 6 \end{bmatrix} = \begin{bmatrix} 4 & 16 \\ 11 & 42 \end{bmatrix}$

In [46]:
# matmul (matrix multiplication)
matrix_muti = matrix_a @ matrix_b
print('*'*25)
print(f'matrix_muti:\n {matrix_muti}')


*************************
matrix_muti:
 tensor([[ 8, 16],
        [ 3,  6]])


## exercise

In [29]:
## performing maths operation on tensors

matrix_a = torch.tensor([[2,3],
            [-1, 2]])
matrix_b = torch.tensor([[1, 2],
            [2, 4]])

print(f'matrix_a:\n {matrix_a}')
print(f'matrix_b:\n {matrix_b}')

# sum
sum_matrix = matrix_a + matrix_b
print('*'*25)
print(f'sum_matrix:\n {sum_matrix}')

# difference
diff_matrix = matrix_a - matrix_b
print('*'*25)
print(f'diff_matrix:\n {diff_matrix}')

# products
product_matrix = matrix_a * matrix_b
print('*'*25)
print(f'product_matrix:\n {product_matrix}')

# matmul (matrix multiplication)
matrix_muti = matrix_a @ matrix_b
print('*'*25)
print(f'matrix_muti:\n {matrix_muti}')

matrix_a:
 tensor([[ 2,  3],
        [-1,  2]])
matrix_b:
 tensor([[1, 2],
        [2, 4]])
*************************
sum_matrix:
 tensor([[3, 5],
        [1, 6]])
*************************
diff_matrix:
 tensor([[ 1,  1],
        [-3, -2]])
*************************
product_matrix:
 tensor([[ 2,  6],
        [-2,  8]])
*************************
matrix_muti:
 tensor([[ 8, 16],
        [ 3,  6]])


### GRADIENT COMPUTATION

1. Compute the gradient of $y = 3x^2 + 6x + 4$     at $x = 2$


In [32]:
# create the tensor object
x = torch.tensor(data = 2.0, requires_grad=True)

# define the equation
y = 3*x**2 + 6*x + 4

# compute the derivative
y.backward()

# get the value of y at x = 2
x.grad

tensor(18.)

2. Compute the gradient of $z = 2xy + 3x^2 + 5y + 3$ at $x = 3$ and $y = 2$


In [36]:
x = torch.tensor(data = 3.0, requires_grad=True)
y = torch.tensor(data = 2.0, requires_grad=True)

z = 2 * x * y + 3 * x **2 + 5 *y + 3

z.backward()

print(x.grad)
print(y.grad)

tensor(22.)
tensor(11.)


3. Compute the value of $z = \sqrt{2x^2 + 5}$
at $x = 5$


In [39]:
x = torch.tensor(data = 1.0, requires_grad=True)

z = (2 * x ** 2 + 5) ** (1/2)

z.backward()

print(x.grad)

tensor(0.7559)


In [41]:
2/(7 ** 0.5)

0.7559289460184544